export const SECTORS = [
  { type: "restaurant", label: "Restaurant", icon: "🍽️" },
  { type: "cafe", label: "Café", icon: "☕" },
  { type: "bar", label: "Bar", icon: "🍺" },
  { type: "bakery", label: "Boulangerie", icon: "🥐" },
  { type: "beauty_salon", label: "Salon de beauté", icon: "💅" },
  { type: "hair_care", label: "Coiffeur", icon: "✂️" },
  { type: "gym", label: "Salle de sport", icon: "🏋️" },
  { type: "laundry", label: "Pressing/Laverie", icon: "👕" },
  { type: "clothing_store", label: "Vêtements", icon: "🛍️" },
  { type: "pharmacy", label: "Pharmacie", icon: "💊" },
  { type: "doctor", label: "Médecin", icon: "🩺" },
  { type: "dentist", label: "Dentiste", icon: "🦷" },
  { type: "car_repair", label: "Garage auto", icon: "🔧" },
  { type: "plumber", label: "Plombier", icon: "🪠" },
  { type: "electrician", label: "Électricien", icon: "⚡" },
  { type: "locksmith", label: "Serrurier", icon: "🔐" },
  { type: "florist", label: "Fleuriste", icon: "🌸" },
  { type: "lodging", label: "Hôtel / B&B", icon: "🏨" },
  { type: "real_estate_agency", label: "Agence immo", icon: "🏠" },
  { type: "accounting", label: "Comptable", icon: "📊" },
];

export const RADIUS_OPTIONS = [
  { value: "1000", label: "1 km" },
  { value: "2000", label: "2 km" },
  { value: "5000", label: "5 km" },
  { value: "10000", label: "10 km" },
  { value: "20000", label: "20 km" },
  { value: "50000", label: "50 km" },
];
